"""Technical disclaimer layer for oracle outputs.

Per design doc section 29.2: every response must include research disclaimer,
warning against use in critical decisions, and emphasis on exploratory nature.
"""
import hashlib
import time


class DisclaimerGenerator:
    """Generates multi-layer disclaimers for oracle outputs."""

    PRIMARY_DISCLAIMER = (
        "This response is generated by an evolved symbolic computational structure. "
        "It does NOT constitute scientific, medical, legal, or financial advice."
    )

    RESEARCH_DISCLAIMER = (
        "This system is a research laboratory for evolutionary symbolic computation. "
        "It explores novel algorithmic structures combining ancient symbolic systems "
        "with modern evolutionary algorithms. No empirical or scientific claims "
        "of predictive accuracy are made."
    )

    WARNING_DISCLAIMER = (
        "Do NOT use this output for critical decisions including but not limited to: "
        "medical treatment, legal proceedings, financial investments, "
        "emergency response, or mental health decisions."
    )

    NATURE_DISCLAIMER = (
        "The system uses symbolic computation from ancient traditions "
        "(astrology, I Ching, gematria, numerology, etc.) as computational substrate, "
        "not as literal truth claims. The evolutionary process explores "
        "new algorithmic structures, not mystical truths."
    )

    @classmethod
    def generate_full_disclaimer(cls) -> str:
        """Generate the complete disclaimer text."""
        return "\n\n".join([
            cls.PRIMARY_DISCLAIMER,
            cls.RESEARCH_DISCLAIMER,
            cls.WARNING_DISCLAIMER,
            cls.NATURE_DISCLAIMER,
        ])

    @classmethod
    def generate_brief_disclaimer(cls) -> str:
        """Generate a brief one-line disclaimer."""
        return (
            "Evolved symbolic structure - not scientific advice. "
            "For research purposes only."
        )

    @classmethod
    def generate_output_disclaimer(
        cls,
        oracle_id: str,
        generation: int,
        confidence: float,
    ) -> dict:
        """Generate structured disclaimer with oracle metadata."""
        full = cls.generate_full_disclaimer()
        content_hash = hashlib.sha256(full.encode()).hexdigest()[:16]

        return {
            "text": full,
            "brief": cls.generate_brief_disclaimer(),
            "content_hash": content_hash,
            "oracle_id": oracle_id,
            "generation": generation,
            "confidence": confidence,
            "timestamp": time.time(),
            "disclaimer_version": "1.0",
        }

    @classmethod
    def should_include_full(cls, confidence: float) -> bool:
        """Determine if full disclaimer should be included based on confidence."""
        return True  # Always include for safety

    @classmethod
    def get_risk_level(cls, confidence: float, domain: str = "general") -> str:
        """Assess risk level of the output."""
        high_risk_domains = {"medical", "financial", "legal", "emergency", "mental_health"}
        if domain in high_risk_domains:
            return "CRITICAL"
        if confidence > 0.7:
            return "HIGH_CONFIDENCE"
        if confidence > 0.3:
            return "MODERATE"
        return "LOW"
