"""Explanation trace generator for oracle outputs."""


def generate_explanation(oracle_result: dict, execution_trace: list[dict] = None) -> dict:
    """Generate a structured explanation of how the oracle arrived at its answer."""
    dominant_systems = oracle_result.get("dominant_systems", [])
    fitness = oracle_result.get("fitness", {})
    confidence = oracle_result.get("oracle_confidence", 0.0)
    numeric_sig = oracle_result.get("numeric_signature", [])

    explanation_lines = []

    explanation_lines.append(f"Oracle structure uses {len(dominant_systems)} symbolic system(s): {', '.join(dominant_systems)}.")

    if fitness:
        coherence = fitness.get("structural_coherence", 0)
        stability = fitness.get("response_stability", 0)
        novelty = fitness.get("novelty_score", 0)
        explanation_lines.append(f"Structural coherence: {coherence:.2f}, Response stability: {stability:.2f}, Novelty: {novelty:.2f}")

    explanation_lines.append(f"Overall confidence: {confidence:.2f}")

    if numeric_sig:
        explanation_lines.append(f"Numeric signature length: {len(numeric_sig)} values, range: [{min(numeric_sig):.2f}, {max(numeric_sig):.2f}]")

    return {
        "explanation_text": " ".join(explanation_lines),
        "structured": {
            "systems_used": dominant_systems,
            "system_count": len(dominant_systems),
            "fitness_summary": fitness,
            "confidence_level": "high" if confidence > 0.7 else "medium" if confidence > 0.4 else "low",
            "signature_stats": {
                "length": len(numeric_sig),
                "mean": sum(numeric_sig) / len(numeric_sig) if numeric_sig else 0,
                "variance": sum((x - sum(numeric_sig)/len(numeric_sig))**2 for x in numeric_sig) / len(numeric_sig) if numeric_sig else 0,
            },
        },
        "disclaimer": "This output is generated by an evolved symbolic computational structure. It does not constitute scientific, medical, financial, or legal advice. The system is a research exploratory tool.",
    }
