"""Enhanced Oracle Output generation with multi-layer output, explanation trace,
confidence model, and comprehensive metadata.

Per design doc section 24: OracleOutput must include answer, symbolic_answer,
numeric_signature, oracle_confidence, dominant_systems, evolved_structure,
explanation_trace, lineage_id, generation, and fitness.
"""
import time
import hashlib
import json
import math
from dataclasses import dataclass, field
from typing import Optional
from ..genome.chromosome import Chromosome
from .disclaimer import DisclaimerGenerator


@dataclass
class OracleOutput:
    """Multi-layer oracle output per design doc section 24."""
    answer: str
    symbolic_answer: dict = field(default_factory=dict)
    numeric_signature: list[float] = field(default_factory=list)
    oracle_confidence: float = 0.0
    dominant_systems: list[str] = field(default_factory=list)
    evolved_structure: dict = field(default_factory=dict)
    explanation_trace: list[str] = field(default_factory=list)
    lineage_id: str = ""
    generation: int = 0
    fitness: dict = field(default_factory=dict)
    disclaimer: dict = field(default_factory=dict)
    confidence_model: dict = field(default_factory=dict)
    system_contributions: list[dict] = field(default_factory=list)
    fusion_info: dict = field(default_factory=dict)
    output_hash: str = ""
    timestamp: float = 0.0

    def to_dict(self) -> dict:
        return {
            "answer": self.answer,
            "symbolic_answer": self.symbolic_answer,
            "numeric_signature": self.numeric_signature,
            "oracle_confidence": self.oracle_confidence,
            "dominant_systems": self.dominant_systems,
            "evolved_structure": self.evolved_structure,
            "explanation_trace": self.explanation_trace,
            "lineage_id": self.lineage_id,
            "generation": self.generation,
            "fitness": self.fitness,
            "disclaimer": self.disclaimer,
            "confidence_model": self.confidence_model,
            "system_contributions": self.system_contributions,
            "fusion_info": self.fusion_info,
            "output_hash": self.output_hash,
            "timestamp": self.timestamp,
        }


class ConfidenceModel:
    """Multi-factor confidence estimation for oracle outputs."""

    def __init__(self):
        self.factors = {}

    def estimate(
        self,
        chromosome: Chromosome,
        execution_result: dict,
        fitness: dict,
    ) -> dict:
        """Estimate confidence from multiple factors."""
        gene_count = len(chromosome.genes) if hasattr(chromosome, 'genes') else 0
        edge_count = len(chromosome.edges) if hasattr(chromosome, 'edges') else 0

        structural = fitness.get("structural_coherence", 0)
        stability = fitness.get("response_stability", 0)
        convergence = fitness.get("symbolic_convergence", 0)
        entropy_use = fitness.get("entropy_utilization", 0)
        pure_entropy = fitness.get("pure_entropy_fitness", 0)
        historical = fitness.get("historical_accuracy_fitness", 0)

        factors = {
            "structural_coherence": structural,
            "response_stability": stability,
            "symbolic_convergence": convergence,
            "entropy_utilization": entropy_use,
            "pure_entropy_fitness": pure_entropy,
            "historical_accuracy": historical,
            "gene_diversity": min(gene_count / 5, 1.0) if gene_count > 0 else 0,
            "graph_complexity": min(edge_count / max(gene_count - 1, 1), 1.0) if gene_count > 1 else 0,
        }

        weights = {
            "structural_coherence": 0.15,
            "response_stability": 0.15,
            "symbolic_convergence": 0.10,
            "entropy_utilization": 0.10,
            "pure_entropy_fitness": 0.15,
            "historical_accuracy": 0.15,
            "gene_diversity": 0.10,
            "graph_complexity": 0.10,
        }

        weighted_sum = sum(factors[k] * weights[k] for k in factors)
        confidence = 1 / (1 + math.exp(-5 * (weighted_sum - 0.5)))

        return {
            "confidence": confidence,
            "factors": factors,
            "weights": weights,
            "weighted_sum": weighted_sum,
            "level": "high" if confidence > 0.7 else "medium" if confidence > 0.4 else "low",
        }


class OracleOutputBuilder:
    """Builds comprehensive OracleOutput per design doc section 24."""

    DISCLAIMER = {
        "text": "This response is generated by an evolved symbolic computational structure. "
                "It does NOT constitute scientific, medical, legal, or financial advice.",
        "risk_level": "high",
    }

    def build(
        self,
        chromosome: Chromosome,
        execution_result: dict,
        entropy_packet: dict,
        generation: int = 0,
    ) -> OracleOutput:
        fused_numeric = execution_result.get("fused_numeric", [])
        fused_structural = execution_result.get("fused_structural", {})
        execution_confidence = execution_result.get("oracle_confidence", 0.0)

        systems = list(set(g.system_id for g in chromosome.gene_list))
        fitness = chromosome.fitness

        confidence_model = ConfidenceModel()
        conf_info = confidence_model.estimate(chromosome, execution_result, fitness)

        answer = self._generate_answer(fused_numeric, fused_structural, conf_info, systems)
        symbolic_answer = self._generate_symbolic_answer(fused_structural, systems)
        explanation = self._generate_explanation(chromosome, execution_result, conf_info)
        system_contributions = self._compute_system_contributions(chromosome, execution_result)
        fusion_info = self._compute_fusion_info(chromosome)
        evolved_structure = self._compute_evolved_structure(chromosome, systems)

        disclaimer = DisclaimerGenerator.generate_output_disclaimer(
            oracle_id=chromosome.chromosome_id,
            generation=generation,
            confidence=conf_info["confidence"],
        )

        chrom_id = getattr(chromosome, 'chromosome_id', None) or "unknown"
        output = OracleOutput(
            answer=answer,
            symbolic_answer=symbolic_answer,
            numeric_signature=fused_numeric[:20],
            oracle_confidence=conf_info["confidence"],
            dominant_systems=systems,
            evolved_structure=evolved_structure,
            explanation_trace=explanation,
            lineage_id=chromosome.lineage_id or chrom_id,
            generation=generation,
            fitness=fitness,
            disclaimer=disclaimer,
            confidence_model=conf_info,
            system_contributions=system_contributions,
            fusion_info=fusion_info,
            timestamp=time.time(),
        )

        output.output_hash = self._compute_output_hash(output)
        return output

    def _generate_answer(
        self,
        numeric: list[float],
        structural: dict,
        conf_info: dict,
        systems: list[str],
    ) -> str:
        confidence = conf_info["confidence"]
        level = conf_info["level"]

        if not numeric:
            return "Insufficient data for oracle response."

        balance = structural.get("yin_yang_balance", 0.5)
        convergence = structural.get("symbolic_convergence", 0.5)

        polarity = (
            "balanced" if 0.4 <= balance <= 0.6
            else ("yang-oriented" if balance > 0.6 else "yin-oriented")
        )

        phase = "transition"
        if convergence > 0.7:
            phase = "integration"
        elif convergence < 0.3:
            phase = "emergence"

        return (
            f"The evolved oracle structure ({level} confidence, {confidence:.2f}) "
            f"draws from {len(systems)} symbolic system(s): {', '.join(systems)}. "
            f"Phase: {phase}. Polarity: {polarity}. "
            f"Cross-system resonance: {'high' if convergence > 0.6 else 'moderate'}."
        )

    def _generate_symbolic_answer(self, structural: dict, systems: list[str]) -> dict:
        balance = structural.get("yin_yang_balance", 0.5)
        complexity = structural.get("binary_complexity", 0.5)

        polarity = (
            "expansion" if balance > 0.6
            else ("contraction" if balance < 0.4 else "equilibrium")
        )
        phase = (
            "integration" if complexity > 0.7
            else ("transition" if complexity > 0.4 else "emergence")
        )

        return {
            "phase": phase,
            "polarity": polarity,
            "dominant_pattern": systems[0] if systems else "unknown",
            "system_diversity": len(systems),
            "balance_score": balance,
            "complexity_score": complexity,
        }

    def _generate_explanation(self, chrom, result: dict, conf_info: dict) -> list[str]:
        trace = []
        gene_count = len(chrom.genes) if hasattr(chrom, 'genes') else 0
        edge_count = len(chrom.edges) if hasattr(chrom, 'edges') else 0
        fusion_method = (
            chrom.fusion_schema.get('method', 'default')
            if hasattr(chrom, 'fusion_schema') else 'weighted_average'
        )

        trace.append(f"Oracle composed of {gene_count} symbolic system(s)")
        for gene in chrom.gene_list:
            gene_id = getattr(gene, 'gene_id', None) or "unknown"
            weight = getattr(gene, 'weight', 0.0)
            trace.append(f"  - Gene {gene_id}: {gene.system_id} (weight={weight:.2f})")
        trace.append(f"Graph edges: {edge_count}")
        trace.append(f"Fusion method: {fusion_method}")
        trace.append(f"Confidence: {conf_info['confidence']:.2f} ({conf_info['level']})")

        for factor, value in conf_info["factors"].items():
            trace.append(f"  - {factor}: {value:.2f}")

        return trace

    def _compute_system_contributions(self, chrom, result: dict) -> list[dict]:
        contributions = []
        for gene in chrom.gene_list:
            contributions.append({
                "system_id": gene.system_id,
                "gene_id": getattr(gene, 'gene_id', 'unknown'),
                "weight": getattr(gene, 'weight', 0.0),
                "backend": getattr(gene, 'backend', 'unknown'),
            })
        return contributions

    def _compute_fusion_info(self, chrom) -> dict:
        return {
            "method": chrom.fusion_schema.get("method", "weighted_average")
            if hasattr(chrom, 'fusion_schema') else "weighted_average",
            "edge_count": len(chrom.edges) if hasattr(chrom, 'edges') else 0,
            "has_feedback": any(
                chrom.edges[i][1] == chrom.edges[j][0]
                for i in range(len(chrom.edges))
                for j in range(len(chrom.edges))
            ) if hasattr(chrom, 'edges') else False,
        }

    def _compute_evolved_structure(self, chrom, systems: list[str]) -> dict:
        gene_count = len(chrom.genes) if hasattr(chrom, 'genes') else 0
        edge_count = len(chrom.edges) if hasattr(chrom, 'edges') else 0
        return {
            "gene_count": gene_count,
            "edge_count": edge_count,
            "systems": systems,
            "representation": getattr(chrom, 'representation', 'graph'),
            "depth": getattr(chrom, 'depth', 1),
            "has_custom_formulas": bool(getattr(chrom, 'custom_formulas', {})),
            "has_invented_methods": bool(getattr(chrom, 'invented_methods', [])),
        }

    def _compute_output_hash(self, output: 'OracleOutput') -> str:
        content = json.dumps({
            "answer": output.answer,
            "numeric": output.numeric_signature,
            "confidence": output.oracle_confidence,
            "systems": output.dominant_systems,
            "lineage": output.lineage_id,
            "generation": output.generation,
        }, sort_keys=True)
        return hashlib.sha256(content.encode()).hexdigest()[:16]
